{
    'name': 'SuperTCG Events',
    'version': '1.2.4',
    'category': 'Marketing/Events',
    'summary': 'Recurring events with weekly copies, POS barcodes, and location-based landing pages',
    'description': 'Custom module for SuperTCG to manage recurring weekly events with automatic copies, POS barcode integration, and location-based landing pages.',
    'author': 'SuperTCG',
    'license': 'LGPL-3',
    'website': 'https://dev.supertcg.be',
    'depends': [
        'event',
        'event_sale',
        'website',
        'website_event',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/event_stage_data.xml',
        'data/ir_cron_data.xml',
        'views/waitlist_views.xml',
        'views/event_views.xml',
        'views/event_registration_views.xml',
        'views/event_landing_templates.xml',
        'views/waitlist_templates.xml',
        'views/pay_at_venue_templates.xml',
        'views/event_ticket_templates.xml',
        'views/mail_template_pos_barcode.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'auto_install': False,
}
