{
    'name': 'SuperTCG Products',
    'version': '1.1.0',
    'category': 'Sales/Sales',
    'summary': 'Streamlined TCG card entry with camera, bulk mode, and auto barcode printing.',
    'description': 'Custom module for SuperTCG to rapidly enter second-hand TCG cards into the product catalog and publish them to the eCommerce storefront. Features include mobile-first card entry with camera, bulk mode, auto barcode labels, intake wizard for buy-in and consignment, eWallet store credit, and batch finalization with financial settlement.',
    'author': 'SuperTCG',
    'license': 'LGPL-3',
    'website': 'https://dev.supertcg.be',
    'depends': [
        'product',
        'stock',
        'account',
        'purchase',
        'website_sale',
        'sale_loyalty',
        'hr',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/tcg_intake_wizard_views.xml',
        'views/tcg_consignment_settlement_views.xml',
        'views/consignment_dashboard_templates.xml',
        'views/consignment_print_overview_template.xml',
        'views/menu_actions.xml',
        'views/dashboard_templates.xml',
        'views/aankoop_dashboard_templates.xml',
        'views/tcg_margin_dashboard_template.xml',
        'views/tcg_hub_dashboard_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'supertcg_products/static/src/css/tcg_card_form.css',
            'supertcg_products/static/src/tcg_card_form/tcg_card_form.js',
            'supertcg_products/static/src/tcg_card_form/tcg_card_form.xml',
            'supertcg_products/static/src/tcg_ocr_form/tcg_ocr_form.js',
            'supertcg_products/static/src/tcg_ocr_form/tcg_ocr_form.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'supertcg_products/static/description/icon.png',
}
