apiVersion: 1

datasources:
  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    access: proxy
    url: http://odoo-alertmanager:9093
    jsonData:
      implementation: prometheus
    editable: false
